### ISSUE TITLE
cython setup

### ISSUE THREAD

**Issue by IbtihalFerwana** [pkuyzy/TLC-GNN#1]
Hello, 
Is there some steps one should take to get the cython script working at your repository?
I tried to compile the `.pyx` file as in here: https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html  but that did not help.

I'll appreciate your advice.

**Comment by pkuyzy** [comment]
I have updated the readme file, please see the "Setup Cython" part.

**Comment by IbtihalFerwana** [comment]
Thanks, 
what worked with me is your second suggestion: `copy the code in ./sg2dgm/persistenceImager.pyx to a new file named ./sg2dgm/persistenceImager.py,`
